### PR TITLE
Relax dependency on Money gem

### PR DESCRIPTION
**Pull request by ahegyi**
This PR:
- Updates the ruby version to 2.6.6
- Relaxes the dependency on the money gem
- Updates specs to conform to more modern rspec standards

### CODE REVIEW

**Comment by ahegyi** [comment]
Ran the specs locally and they passed...

**Comment by chris** [comment]
@chaslemley or whoever - you guys should probably remove me from this repo :)

**Comment by jgeggatt** [comment]
me too :)

**Comment by drinkzima** [comment]
👀 reunion!  (also can purge me too)

**Comment by NikolaiSa** [comment]
Ditto!

**Comment by jmschultz** [comment]
Not me. I want to feel like I’m still on the team.

**Comment by callumj** [comment]
> @chaslemley or whoever - you guys should probably remove me from this repo :)

This is a public repo, we should just make it private.

**Comment by chris** [comment]
LOL, I forgot - it's like the one open source thing we did!

**Comment by kgann** [comment]
In before it's private.

**Review by ricardohsd — APPROVED** [review]
LGTM

**Comment by ahegyi** [comment]
FYI all former HT folks, feel free to remove yourself as a watcher if you'd prefer to ignore these updates :)

**Pull request merged**
